### ISSUE TITLE
Pipeline is not picking up all bam/crams in directory

### ISSUE THREAD

**Issue by srynobio** [brwnj/smoove-nf#1]
Were testing out your workflow and have ran into the following issue:

Using the following command:

```
nextflow run main.nf -c nextflow.config --bams path/*.cram --bed regions.bed --fasta human_g1k_v37_decoy_phix.fasta --gff my.gff3
```
I expect (based on your option) for all of my 484 cram file to be processed, but only one is being process, which eventually errors out because your downstream `merge` step expects more then one file.

```
--bams
Aligned sequences in .bam and/or .cram format. Indexes (.bai/.crai) must be present.
Use wildcards like 'SRP1234/alignments/*.cram' to simplify specifying all of your alignment files.
```

**Comment by brwnj** [comment]
bash is expanding your wildcards, hence the single quote in the example. You should be okay with:

```
nextflow run main.nf -c nextflow.config --bams 'path/*.cram' --bed regions.bed --fasta human_g1k_v37_decoy_phix.fasta --gff my.gff3
```

**Comment by srynobio** [comment]
@brwnj thanks! I see that now, but it was really easy to miss.

**Comment by brwnj** [comment]
I'll work on the docs to make it clearer with a full example.
